@url = https://organic-guide-jxprjwpq66g2jp96-8080.app.github.dev/filmes

GET {{url}}

###

GET {{url}}/7

###

POST {{url}}
Content-Type: application/json

{
    "titulo" : "Sword Art Online",
    "idGenero" : 1
}

###

PUT {{url}}/2
Content-Type: application/json

{
    "titulo": "A Freira",
    "idGenero": 2
}

###

DELETE {{url}}/2