@url = https://verbose-space-waddle-px57jq5pqx737g4w-8080.app.github.dev/funcao

GET {{url}}

###

GET {{url}}/3

###

POST {{url}}
Content-Type: application/json

{
    "descricao" : "Protagonista"
}

###

PUT {{url}}/1
Content-Type: application/json

{
    "descricao": "Antagonista"
}

###

DELETE {{url}}/2
