@url = https://organic-guide-jxprjwpq66g2jp96-8080.app.github.dev/generos

POST {{url}}
Content-Type: application/json

{
    "nome": "Anime"
}

###

GET {{url}}

###

GET {{url}}/4

###

PUT {{url}}/9
Content-Type: application/json

{
    "nome": "Presidente"
}

###

DELETE {{url}}/9
